api_param_error = "Parameter error"
api_operate_success = "Operated"
api_operate_fail = "Operate failed"
api_submit_success = "Submitted"
api_add_success = "Added"
api_update_success = "Updated"
api_delete_success = "Deleted"
api_delete_fail = "delete failed"
api_clear_success = "Cleared"
api_upload_success = "Updated"
api_register_success = "Registration success"
api_enable_success = "Enabled"
api_disable_success = "Disabled"