api_param_error = "参数错误"
api_operate_success = "操作成功"
api_operate_fail = "操作失败"
api_submit_success = "提交成功"
api_add_success = "添加成功"
api_update_success = "更新成功"
api_delete_success = "删除成功"
api_delete_fail = "删除失败"
api_clear_success = "清除成功"
api_upload_success = "上传成功"
api_register_success = "注册成功"
api_enable_success = "启用成功"
api_disable_success = "禁用成功"